using System.Text;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using htmxRazor.Demo.Models;

namespace htmxRazor.Demo.Pages;

public class ThemeBuilderModel : PageModel
{
    public Dictionary<string, List<ThemeToken>> TokensByCategory { get; } = new()
    {
        ["Semantic Colors"] = new()
        {
            new("--rhx-color-bg", "Semantic Colors", "Background", "color", "#fafafa"),
            new("--rhx-color-surface", "Semantic Colors", "Surface", "color", "#ffffff"),
            new("--rhx-color-surface-raised", "Semantic Colors", "Surface Raised", "color", "#ffffff"),
            new("--rhx-color-text", "Semantic Colors", "Text", "color", "#171717"),
            new("--rhx-color-text-muted", "Semantic Colors", "Text Muted", "color", "#737373"),
            new("--rhx-color-border", "Semantic Colors", "Border", "color", "#d4d4d4"),
            new("--rhx-color-border-muted", "Semantic Colors", "Border Muted", "color", "#e5e5e5"),
            new("--rhx-color-focus-ring", "Semantic Colors", "Focus Ring", "color", "#3b82f6"),
        },
        ["Color Palette: Brand"] = BuildPalette("brand", "#eff6ff", "#dbeafe", "#bfdbfe", "#93c5fd", "#60a5fa", "#3b82f6", "#2563eb", "#1d4ed8", "#1e40af", "#1e3a8a", "#172554"),
        ["Color Palette: Neutral"] = BuildPalette("neutral", "#fafafa", "#f5f5f5", "#e5e5e5", "#d4d4d4", "#a3a3a3", "#737373", "#525252", "#404040", "#262626", "#171717", "#0a0a0a"),
        ["Color Palette: Success"] = BuildPalette("success", "#f0fdf4", "#dcfce7", "#bbf7d0", "#86efac", "#4ade80", "#22c55e", "#16a34a", "#15803d", "#166534", "#14532d", "#052e16"),
        ["Color Palette: Warning"] = BuildPalette("warning", "#fffbeb", "#fef3c7", "#fde68a", "#fcd34d", "#fbbf24", "#f59e0b", "#d97706", "#b45309", "#92400e", "#78350f", "#451a03"),
        ["Color Palette: Danger"] = BuildPalette("danger", "#fef2f2", "#fee2e2", "#fecaca", "#fca5a5", "#f87171", "#ef4444", "#dc2626", "#b91c1c", "#991b1b", "#7f1d1d", "#450a0a"),
        ["Typography"] = new()
        {
            new("--rhx-font-family", "Typography", "Font Family", "text", "system-ui, -apple-system, sans-serif"),
            new("--rhx-font-family-mono", "Typography", "Mono Font", "text", "ui-monospace, SFMono-Regular, monospace"),
            new("--rhx-font-size-xs", "Typography", "Size XS", "text", "0.75rem"),
            new("--rhx-font-size-sm", "Typography", "Size SM", "text", "0.875rem"),
            new("--rhx-font-size-md", "Typography", "Size MD", "text", "1rem"),
            new("--rhx-font-size-lg", "Typography", "Size LG", "text", "1.125rem"),
            new("--rhx-font-size-xl", "Typography", "Size XL", "text", "1.25rem"),
        },
        ["Spacing"] = new()
        {
            new("--rhx-space-xs", "Spacing", "Extra Small", "text", "0.25rem"),
            new("--rhx-space-sm", "Spacing", "Small", "text", "0.5rem"),
            new("--rhx-space-md", "Spacing", "Medium", "text", "0.75rem"),
            new("--rhx-space-lg", "Spacing", "Large", "text", "1rem"),
            new("--rhx-space-xl", "Spacing", "Extra Large", "text", "1.5rem"),
        },
        ["Border Radius"] = new()
        {
            new("--rhx-radius-sm", "Border Radius", "Small", "text", "0.25rem"),
            new("--rhx-radius-md", "Border Radius", "Medium", "text", "0.375rem"),
            new("--rhx-radius-lg", "Border Radius", "Large", "text", "0.5rem"),
            new("--rhx-radius-xl", "Border Radius", "Extra Large", "text", "0.75rem"),
            new("--rhx-radius-full", "Border Radius", "Full", "text", "9999px"),
        },
        ["Shadows"] = new()
        {
            new("--rhx-shadow-sm", "Shadows", "Small", "text", "0 1px 2px rgba(0,0,0,0.05)"),
            new("--rhx-shadow-md", "Shadows", "Medium", "text", "0 4px 6px -1px rgba(0,0,0,0.07), 0 2px 4px -2px rgba(0,0,0,0.05)"),
            new("--rhx-shadow-lg", "Shadows", "Large", "text", "0 10px 15px -3px rgba(0,0,0,0.1), 0 4px 6px -4px rgba(0,0,0,0.05)"),
        },
    };

    private static List<ThemeToken> BuildPalette(string name, params string[] shades)
    {
        var steps = new[] { "50", "100", "200", "300", "400", "500", "600", "700", "800", "900", "950" };
        var tokens = new List<ThemeToken>();
        for (var i = 0; i < steps.Length && i < shades.Length; i++)
        {
            var label = $"{char.ToUpper(name[0])}{name[1..]} {steps[i]}";
            tokens.Add(new ThemeToken($"--rhx-color-{name}-{steps[i]}", $"Color Palette: {char.ToUpper(name[0])}{name[1..]}", label, "color", shades[i]));
        }
        return tokens;
    }

    public void OnGet() { }

    public IActionResult OnPostDownload()
    {
        var sb = new StringBuilder();
        sb.AppendLine("/* htmxRazor Theme Overrides — Generated by Theme Builder */");
        sb.AppendLine(":root {");

        foreach (var form in Request.Form)
        {
            if (form.Key.StartsWith("--rhx-") && !string.IsNullOrWhiteSpace(form.Value))
            {
                sb.AppendLine($"  {form.Key}: {form.Value};");
            }
        }

        sb.AppendLine("}");

        var bytes = Encoding.UTF8.GetBytes(sb.ToString());
        return File(bytes, "text/css", "rhx-theme-overrides.css");
    }
}
